---
- name: Copy files from local host to remote host
  gather_facts: false
  hosts: app
  become: true

  tasks:
    - name: Copy file to remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/nginx/conf.d/
        mode: "0644"
        owner: root
      loop:
        - servers.conf
      tags: copy_file

    - name: Reload Service
      ansible.builtin.service:
        name: nginx
        state: reloaded
      tags: reload
