---
- name: Copy files from local host to remote host
  gather_facts: false
  hosts: app
  become: true

  tasks:
    - name: Copy file to remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/blockchain/wordpress/docker-compose.yml
        mode: "0644"
        owner: blockchain
      loop:
        - wordpress_docker_compose.yml
      tags: copy_file
