---
- name: Copy files from local host to remote host
  gather_facts: false
  hosts: app
  become: true

  tasks:
    - name: Copy file to remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/nginx/conf.d/servers.conf
        mode: "0644"
        owner: root
        group: root
      loop:
        - nginx-ssl.conf

      tags: copy_file
