---
- name: Copy files from local host to remote host
  gather_facts: false
  hosts: app
  become: true

  tasks:
    - name: Copy formio to remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/blockchain/domineum/addons/
        mode: "0644"
        owner: root
      loop:
        - odoo-addons/web_openeducat-11.0.1.0.0 (1).zip
