---
- name: Create directory
  gather_facts: false
  hosts: app
  become: true

  tasks:
    - name: Create directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: root
        group: root
      loop:
        - /etc/nginx/ssl
      tags: create_directory
