---
- name: Create directory
  gather_facts: false
  hosts: app
  become: true

  tasks:
    - name: Create directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: blockchain
        group: blockchain
      loop:
        - /home/blockchain/jobs
      tags: create_directory
