---
- name: Install docker on CentOS
  hosts: app
  gather_facts: No
  become: yes

  vars:
    user: blockchain

  tasks:
    - name: Remove docker if installed
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-engine
        state: removed

    - name: Install yum utils and other packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - bzip2
          - python3-pip
          - python3-setuptools
          - ca-certificates
        state: present

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Install Docker
      package:
        name: docker-ce
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: { { user } }
        groups: docker
        append: yes

    - name: Install Docker Bash Completion Command
      get_url:
        url: https://github.com/docker/docker-ce/blob/master/components/cli/contrib/completion/bash/docker
        dest: /etc/bash_completion.d/docker

    - name: Ensure docker-compose is installed and available
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose

    - name: Make docker compose file executable
      file:
        path: /usr/local/bin/docker-compose
        mode: u=rwx,g=rwx,o=rwx
