---
- name: Install docker on CentOS or Redhat
  hosts: app
  gather_facts: true
  become: true

  vars:
    docker_user: blockchain

  tasks:
    - name: Remove docker if installed
      ansible.builtin.yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-engine
        state: removed

    - name: Install yum utils and other packages
      ansible.builtin.yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - bzip2
          - python3-pip
          - python3-setuptools
          - ca-certificates
        state: present

    - name: set mydistribution
      ansible.builtin.set_fact:
        mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"

    - name: Add signing key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
        state: present

    - name: Add repository into repo.d list
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: true

    - name: Install Docker Bash Completion Command
      get_url:
        url: https://github.com/docker/docker-ce/blob/master/components/cli/contrib/completion/bash/docker
        dest: /etc/bash_completion.d/docker

    - name: Ensure docker-compose is installed and available
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose

    - name: Make docker compose file executable
      file:
        path: /usr/local/bin/docker-compose
        mode: u=rwx,g=rwx,o=rwx

    - name: Create a symbolink link to  /usr/local/bin/docker-compose
      ansible.builtin.file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        owner: root
        group: root
        state: link
