---
- hosts: servers
  become: true
  gather_facts: false

  vars:
    hostname: vps1.domineum.io
    created_username: blockchain

  tasks:
    - name: Ensure NTP (for the synchronization) is installed
      apt: name=ntp state=present

    - name: Ensure NTP is running.
      service: name=ntp state=started enabled=yes

    - name: set timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

    - name: Set a hostname specifying strategy
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd

    - name: Copy Server Welcome Message to server
      ansible.builtin.copy:
        src: motd
        dest: /etc/motd
        owner: root
        mode: "0644"

    - name: Setup passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"

    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ created_username }}"
        state: present
        groups: sudo
        append: true
        create_home: true

    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ created_username }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin prohibit-password"

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - vim
          - git
          - ufw
        state: latest
        update_cache: true

    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Enable and deny by default
      community.general.ufw:
        state: enabled
        default: deny

    # Run the playbook with the command below
    # ansible-playbook new_server.yml -l domineum -u root -k
