---
- name: Install nginx
  hosts: app
  become: true

  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: copy servers.conf file
      ansible.builtin.copy:
        src: servers.conf
        dest: /etc/nginx/conf.d/servers.conf
        owner: root
        mode: "0644"

    - name: Start NGiNX
      service:
        name: nginx
        state: started
