version: "2"
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8075:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./data/odoo:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/posgres:/var/lib/postgresql/data/pgdata
# volumes:
#   odoo-web-data:
#   odoo-db-data:
