---
- name: Install packages
  hosts: app
  become: yes

  tasks:
    - name: Install a list of packages
      yum:
        name:
          - unzip
          - curl
          - git
        state: present
