---
- name: Install packages
  hosts: app
  gather_facts: false
  become: yes

  tasks:
    - name: Install a list of packages
      yum:
        name:
          - unzip
          - curl
          - git
          - python-setuptools
        state: present
