- name: Run using a project directory
  hosts: app
  gather_facts: no
  become: yes

  vars:
    project_folder: /home/blockchain/domineum

  tasks:
    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Create and start services
      community.docker.docker_compose:
        project_src: "{{ project_folder }}"
        state: present
      register: output

    - ansible.builtin.debug:
        var: output
