---
- name: Deploy Docker-Compose to spinup containers 
  gather_facts: No
  hosts: app
  become: false

  var:
    project_src: /home/blockchain/domineum

  tasks:
    - name: deploy Docker-Compose to spinup containers
      docker_compose:
        project_src: "{{ project_src  }}"
        files:
          - docker-compose.yml
