---
- name: Deploy Docker-Compose to spin-up containers
  gather_facts: No
  hosts: app
  become: true

  vars:
    project_src: /home/blockchain/wordpress

  tasks:
    - name: Run docker-compose up -d
      shell:
        cmd: "docker-compose up -d --build"
        chdir: "{{ project_src }}"
