---
- name: Extract archive file to remote server
  gather_facts: false
  hosts: app
  become: true

  vars:
    project_dir: /home/blockchain/domineum/addons/openeducat_erp
    dir_owner: root

  tasks:
    - name: Create destination directory inside the project directroy
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ dir_owner }}"
        group: "{{ dir_owner }}"

    - name: Extract zip file from host to remote machine
      ansible.builtin.unarchive:
        src: odoo-addons/openeducat_erp-11.0.1.0.0.zip
        dest: "{{ project_dir }}"

    - name: Change permission for directory and files
      ansible.builtin.file:
        dest: "{{ project_dir }}"
        mode: "u=rwX,g=rX,o=rX" # change directories to 755 and files to 644
        owner: root
        group: root
        recurse: true
